add express and routes
htmlacademy-nodejs/354189-typoteka-3 pull request #7
Opened 2021-11-10 12:17 UTC by jinonensk

2021-11-14 02:09 UTC, Krabaton requested changes

2021-11-14 02:09 UTC, Krabaton commented on package.json
> +    "start": "nodemon ./src/service/service.js --server 3000",
Нельзя так передавать порт. Он всегда передается через переменную окружения PORT
И тут он же не используется ведь?

2021-11-14 02:09 UTC, Krabaton commented on src/express/express.js
> +const DEFAULT_PORT = 3000;
`const DEFAULT_PORT = process.env.PORT || 3000;`

2021-11-14 02:09 UTC, Krabaton commented on src/express/routes/articles.js
> +  res.send(`/articles/:id ${req.params.id}`)
Надо же было по ТЗ
```  
res.send(`/articles/${req.params.id}`)
```

2021-11-15 15:12 UTC, jinonensk commented on src/express/routes/articles.js
> +  res.send(`/articles/:id ${req.params.id}`)
ну да. точно. Скопировал из ученика что ли

2021-11-15 15:13 UTC, jinonensk commented on src/express/express.js
> +const DEFAULT_PORT = 3000;
поправил

2021-11-15 15:14 UTC, jinonensk commented on package.json
> +    "start": "nodemon ./src/service/service.js --server 3000",
да это же из прошлого аздая. там вроде так и просили сделать. Это не в экспресс

2021-11-16 10:06 UTC, merged