make first pages
htmlacademy-nodejs/354189-typoteka-3 pull request #8
Opened 2021-11-25 16:50 UTC by jinonensk

2021-11-27 10:19 UTC, Krabaton requested changes

2021-11-27 10:19 UTC, Krabaton commented on src/express/templates/layout/layout.pug
> +link(rel='stylesheet' href='css/style.min.css')
Поменять все ссылки на абсолютные - `/css/style.min.cs`

2021-11-27 10:19 UTC, Krabaton commented on src/express/templates/layout/layout.pug
> +script(src='js/vendor.js')
Поменять все ссылки на абсолютные

2021-11-27 10:19 UTC, Krabaton commented on src/express/templates/main.pug
> +            img.last__list-image(src='img/avatar-small-3.png' width='20' height='20' alt='Аватар пользователя')
Поменять все ссылки на абсолютные для картинок тоже.

2021-11-27 10:19 UTC, Krabaton commented on src/express/express.js
> +    headerType: `auth`,
Не очень могу понять, что это за два параметра? К чему мы их пробрасываем в шаблон?

2021-11-27 10:20 UTC, Krabaton commented
Привет. Первый вопрос. Это шаблоны - все данные пробрасываются через шаблон. Это SSR как он есть. На сервере заготовка - шаблон а в браузер уже придет HTML  с данными. Если надо покажу. Второй. Тут видно проблема с путями, насколько понимаю. Надо относительные пути заменить абсолютными. Сейчас там такое link(rel='stylesheet' href='css/style.min.css') а надо поменять link(rel='stylesheet' href='/css/style.min.css') для всех ссылок - на стили, код, графику. И тогда будет правильно все отображаться. Он просто смотрит в папку статики и выбирает оттуда. PUG не отстой) он просто сложный и ошибки в нем искать приключение :(. А так да, имхо для обучения проще было выбрать EJS шаблон

2021-11-30 15:58 UTC, jinonensk commented on src/express/templates/layout/layout.pug
> +link(rel='stylesheet' href='css/style.min.css')
done

2021-11-30 15:58 UTC, jinonensk commented on src/express/templates/layout/layout.pug
> +script(src='js/vendor.js')
done

2021-11-30 15:58 UTC, jinonensk commented on src/express/express.js
> +    headerType: `auth`,
Оставил ьллько параметр с типом хэдера. Потом попнятнее может будет как с ним лучеш поступить. Пока так)

2021-11-30 16:36 UTC, merged